### PR TITLE
Tab data

### PR DESCRIPTION
**Pull request by drjonnicholson**
Problem: Adding dynamic information into the title of a tab is currently restricted to binding on the `title` or `icon` properties. In the case that a dynamic label/badge (e.g. showing a count) is also desired then the `title` slot can be used, but binding there is only updated on refresh (i.e. switching tabs).

To allow changes in the underlying data to properly propagate down through to the `title` slot template we need to use a scoped slot.

This PR adds the ability to bind arbitrary data to a tab that can be used in the `title` slot template. It includes some information available when generating the simple title, and is backwards compatible.

Example on JSFiddle: https://jsfiddle.net/waoa7s60/17/

### CODE REVIEW

**Comment by drjonnicholson** [comment]
Hi @cristijora, any thoughts on this?

**Comment by cristijora** [comment]
Sorry @drjonnicholson Missed this PR. Will review it shortly

**Comment by cristijora** [comment]
Looks good and it's a nice addition @drjonnicholson 
Thanks a lot!

**Comment by drjonnicholson** [comment]
Awesome :) glad to help

**Pull request merged**
